/**********************************************************************************************************************
 * \file IfxClock_init.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include <Clock/IfxClock_init.h>

void IfxClock_switchTo40MHzClock(void)
{

   /* Reconfigure Clock module to use 40MHz clock */
    IfxClock_Config clockConfig;
    IfxClock_initConfig(&clockConfig);

    clockConfig.pllInputClockSelection = IfxClock_PllInputClockSelection_fOsc0; /*fosc0=EXT_CLK*/
    clockConfig.xtalFrequency = 40000000;

    /* System PLL: fPLL0 = 40MHz * 15 / (1 * 2 * 1.0) = 300MHz */
    clockConfig.sysPllConfig.pDivider     = IfxClock_Pdivider_1;
    clockConfig.sysPllConfig.nDivider     = IfxClock_Ndivider_15;
    clockConfig.sysPllConfig.k2Divider    = IfxClock_K2divider_2;
    clockConfig.sysPllConfig.k2PreDivider = IfxClock_K2PreDivider_divBy1_0;

    /* Peripheral PLL: fPLL1 = 40MHz * 30 / (1 * 4 * 1.0) = 300MHz */
    clockConfig.perPllConfig.pDivider     = IfxClock_Pdivider_1;
    clockConfig.perPllConfig.nDivider     = IfxClock_Ndivider_30;
    clockConfig.perPllConfig.k2Divider    = IfxClock_K2divider_4;
    clockConfig.perPllConfig.k2PreDivider = IfxClock_K2PreDivider_divBy1_0;
    clockConfig.perPllConfig.k3Divider    = IfxClock_K3divider_2;
    clockConfig.perPllConfig.k3PreDivider = IfxClock_K3PreDivider_divBy1_0;

    /* CCUCON1: CLKSELQSPI=1(fSOURCE1), QSPIDIV=1 */
    clockConfig.clockDistribution.sysccucon1.mask  |=  (0x3F<<24);  /*mask CLKSELQSPI bitfield*/
    clockConfig.clockDistribution.sysccucon1.value &=~ (0x3F<<24);  /*clear value bitfield*/
    clockConfig.clockDistribution.sysccucon1.value |=  (0x11<<24);  /*CLKSELQSPI=1(fSOURCE1), QSPIDIV=1*/

    IfxClock_init(&clockConfig);

    IfxStm_waitTicks(&MODULE_CPU0, 50000);
}
