/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title Compute the FFT transform on a buffer of ADC readings
 * \abstract CPU0 sets the analog input channel and reads the output of a microphone using STM Timer generated interrupts. Once the buffer is filled CPU1 computes the Fast Fourier Transform (FFT).
 * \description This code example explains how to connect a microphone type KY-038 to the evaluation board, to collect analog sample and to apply a FFT to the data collected.
 *              The microphone type KY-038 is connected to the board with GND, 3.3 V and Analog Out pins.
 *              STM Timer is used to generate a timed interrupt (replacing CCU6 from TC3xx).
 *              The Triggered Modular Analog-to-Digital Converter (TMADC) is used to read a value on channel 0. The reading is performed by the interrupt routine triggered by STM Timer.
 *              Each analog reading is stored in a buffer, once it is filled, a flag is set and the FFT is performed.
 *
 * \name iLLD_TC4D7_LK_ADS_FFT_Frequency_Analyzer_Microphone
 * \version V1.0.0
 * \board AURIX TC4D7 lite Kit, KIT_A3G_TC4D7_LITE, TC4D7XP_A-Step_MC_COM
 * \keywords ADC, TMADC, FFT, STM, Multicore
 * \documents See README.md
 * \lastUpdated 2025-10-06
 *********************************************************************************************************************/
#include <FFT_CCU6.h>
#include "Ifx_Types.h"
#include "Ifx_Cfg.h"
#include "IfxCpu.h"
#include "IfxWtu.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxWtu_disableCpuWatchdog(IfxWtu_getCpuWatchdogPassword());
    IfxWtu_disableSystemWatchdog(IfxWtu_getSystemWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    init_STM_Timer();   /* Initialization of the STM Timer module (replaces CCU6)   */
    init_TMADC();       /* Initialization of the analog to digital converter        */
    start_STM_Timer();  /* Start the STM Timer                                      */

    while(1)
    {
    }
}
