/**********************************************************************************************************************
 * \file FFT_CCU6.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "FFT_CCU6.h"
#include "Ifx_Types.h"
#include "IfxStm_Timer.h"
#include "IfxAdc_Tmadc.h"
#include "Ifx_FftF32.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_STM_TIMER          2                               /* STM Timer interrupt priority              */
#define ISR_PRIORITY_ADC                4                               /* ADC result interrupt's priority           */
#define ADC_SAMPLING_FREQ               20000                           /* ADC sampling frequency in Hz              */

/* Analog Samples Buffer */
#define ANALOG_BUFFER_SIZE 8192
/* Frequency resolution must be power of 2 */
#define FFT_RESOLUTION 128

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* TMADC handles */
IfxAdc_Tmadc         g_tmadc;
IfxAdc_Tmadc_Ch      g_tmadcChannel;
IfxAdc_Tmadc_Config  g_tmadcConfig;
IfxAdc_Tmadc_ChConfig g_tmadcChannel0Config;
IfxAdc_Tmadc_ChannelServReqConfig g_tmadcChannel0ServRequest;

/* STM Timer handle */
IfxStm_Timer g_stmTimer;

/* FFT calculation variables */
cfloat32 g_AnalogSamplesBuffer[ANALOG_BUFFER_SIZE];
cfloat32 g_AnalogSamplesFFT[FFT_RESOLUTION];
float g_FFTAmplitude[FFT_RESOLUTION];
uint16 g_SamplesBufferIndex;
boolean g_bufferReady;

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Function to initialize the STM Timer module (replaces CCU6 on TC4xx) */
void init_STM_Timer(void)
{
    IfxStm_Timer_Config timerConfig;
    IfxStm_Timer_initConfig(&timerConfig, &MODULE_CPU0);

    timerConfig.base.frequency     = ADC_SAMPLING_FREQ;                 /* Set timer frequency to 20 kHz             */
    timerConfig.base.isrPriority   = ISR_PRIORITY_STM_TIMER;           /* Set interrupt priority                    */
    timerConfig.base.isrProvider   = IfxSrc_Tos_cpu0;                  /* Set interrupt service provider             */
    timerConfig.base.minResolution = (1.0f / ADC_SAMPLING_FREQ) / 1000;
    timerConfig.comparator         = IfxStm_Comparator_0;              /* Use comparator 0                          */

    IfxStm_Timer_init(&g_stmTimer, &timerConfig);

    g_bufferReady = FALSE;
}

/* Function to start the STM Timer */
void start_STM_Timer(void)
{
    IfxStm_Timer_run(&g_stmTimer);
}

/* STM Timer Interrupt Service Routine - reads ADC and fills buffer */
IFX_INTERRUPT(ISR_STM_Timer, 0, ISR_PRIORITY_STM_TIMER);

void ISR_STM_Timer(void)
{
    IfxStm_Timer_acknowledgeTimerIrq(&g_stmTimer);

    if(g_bufferReady == FALSE)
    {
        /* Read the result from the TMADC channel */
        int conversionResult = IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel);
        g_AnalogSamplesBuffer[g_SamplesBufferIndex].real = (float32)conversionResult;
        g_SamplesBufferIndex = g_SamplesBufferIndex + 1;
        if(g_SamplesBufferIndex >= ANALOG_BUFFER_SIZE)
        {
            g_SamplesBufferIndex = 0;
            g_bufferReady = TRUE;
        }
    }
}

/* Function to initialize the TMADC (replaces EVADC on TC4xx) */
void init_TMADC(void)
{
    init_TMADC_module();    /* Initialize the TMADC module  */
    init_TMADC_channel();   /* Initialize the TMADC channel */

    /* Start the TMADC module */
    IfxAdc_Tmadc_runModule(&g_tmadc);
}

/* Function to initialize the TMADC module */
void init_TMADC_module(void)
{
    /* Enable ADC module */
    IfxAdc_enableModule(&MODULE_ADC);

    /* Initialize module to default */
    IfxAdc_Tmadc_initModuleConfig(&g_tmadcConfig, &MODULE_ADC);

    /* Change TMADC configuration */
    g_tmadcConfig.id        = IfxAdc_TmadcModule_0;                    /* Module ID                                 */
    g_tmadcConfig.calEnable = 1;                                       /* Calibration enabled                       */

    /* Initialize TMADC module with updated configuration */
    IfxAdc_Tmadc_initModule(&g_tmadc, &g_tmadcConfig);
}

/* Function to initialize the TMADC channel */
void init_TMADC_channel(void)
{
    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&g_tmadcChannel0Config, &MODULE_ADC);

    /* Change TMADC channel configuration */
    g_tmadcChannel0Config.id             = IfxAdc_TmadcChannel_0;      /* Channel ID                                */
    g_tmadcChannel0Config.moduleId       = IfxAdc_TmadcModule_0;       /* Select TMADC module                       */
    g_tmadcChannel0Config.samplingTimeNS = 100;                        /* Set sampling time period                   */
    g_tmadcChannel0Config.mode           = IfxAdc_TmadcOpMode_continuous; /* Select operating mode - continuous      */
    g_tmadcChannel0Config.core           = IfxAdc_TmadcSarCore_0;      /* Select TMADC SAR core                     */

    g_tmadcChannel0Config.resultCfg.resultReg   = IfxAdc_TmadcResultReg_0; /* Configure result register             */
    g_tmadcChannel0Config.resultCfg.waitForRead = 1;                   /* Enable wait-for-read mode                 */

    /* Set channel service request */
    g_tmadcChannel0ServRequest.errorNode    = IfxAdc_TmadcServReq_none;   /* No error service request               */
    g_tmadcChannel0ServRequest.boundaryNode = IfxAdc_TmadcServReq_none;   /* No boundary service request            */
    g_tmadcChannel0ServRequest.resultNode   = IfxAdc_TmadcServReq_0;      /* Result service request node 0          */

    /* Assign configured channel service request to configuration */
    g_tmadcChannel0Config.channelSrvReq = &g_tmadcChannel0ServRequest;

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel, &g_tmadcChannel0Config);
}

/* Computing the FFT and calculate the amplitude */
void compute_FFT()
{
    if(g_bufferReady == TRUE)
    {
        Ifx_FftF32_radix2(g_AnalogSamplesFFT, g_AnalogSamplesBuffer, FFT_RESOLUTION);
        for(int i = 0; i < FFT_RESOLUTION; i++)
        {
            /* Amplitude of FFT is SQRT(RE^2+IM^2) */
            g_FFTAmplitude[i] = pow(g_AnalogSamplesFFT[i].real, 2);
            g_FFTAmplitude[i] = g_FFTAmplitude[i] + pow(g_AnalogSamplesFFT[i].imag, 2);
            g_FFTAmplitude[i] = sqrt(g_FFTAmplitude[i]);
        }
        g_bufferReady = FALSE;
    }
}
