/**********************************************************************************************************************
 * \file EGTM_ATOM_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "EGTM_ATOM_PWM.h"
#include "Ifx_Types.h"
#include "IfxEgtm_Pwm.h"
#include "IfxPort.h"
#include "IfxPort_Pinmap.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NUM_OF_PWM_CHANNELS     (1)                                    /* Number of PWM complementary pairs          */
#define PWM_FREQUENCY           (20000)                                /* PWM frequency in [Hz]                      */
#define PWM_DUTY                (0.0f)                                 /* Initial PWM duty cycle in [%]              */
#define PWM_OUT                 &IfxEgtm_ATOM0_4_TOUT14_P00_5_OUT      /* LED which is driven by the PWM, P00.5      */
#define PWM_MAX_DUTY            (100.0f)                               /* Maximum PWM duty cycle for the ATOM        */
#define FADE_STEP               (PWM_MAX_DUTY / 100.0f)                /* PWM duty cycle step for the ATOM           */
#define CLK_FREQ                 1000000.0f                            /* CMU clock frequency, in Hertz              */
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
        IfxEgtm_Pwm          pwm;                                /* PWM Driver handle                                 */
        IfxEgtm_Pwm_Channel  channels[NUM_OF_PWM_CHANNELS];      /* Array containing channel data after configuration */
        float32             dutyCycles[NUM_OF_PWM_CHANNELS];    /* Duty Cycle values to hold                         */
        float32             phases[NUM_OF_PWM_CHANNELS];        /* Phase Shift values to hold                        */
        IfxEgtm_Pwm_DeadTime deadTimes[NUM_OF_PWM_CHANNELS];     /* Dead times values to hold                         */
} EgtmAtomPwm;

/********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IFX_STATIC EgtmAtomPwm g_egtmAtomPwm;                           /* Structure for PWM generation                      */
float32 g_fadeValue = 0;                                        /* Fade value, starting from 0                       */
sint8 g_fadeDir = 1;                                            /* Fade direction variable                           */

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/
void setDutyCycle(float32 dutyCycle);                           /* Function to set the duty cycle of the PWM         */

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/

/* This function initializes the ATOM PWM */
void initEgtmAtomPwm(void)
{
    /*****************************************************************************************************************/
    /* PWM Configuration                                                                                             */
    /*****************************************************************************************************************/

    /* Configuration variables
     * Neither application (in most of the cases) nor the PWM driver need configuration variables post initialization.
     * It is recommended to define such variables within the function (local), alternatively such structures could
     * also be initialized (element-wise) as constant (in FLASH)
     */
    IfxEgtm_Pwm_Config pwmConfig;                                            /* Main PWM configuration structure      */
    IfxEgtm_Pwm_ChannelConfig channelConfig[NUM_OF_PWM_CHANNELS];            /* Channel configuration structure       */
    IfxEgtm_Pwm_OutputConfig outputConfig[NUM_OF_PWM_CHANNELS];              /* Output configuration structure        */

    /* 1. Configuration structure initialization */
    IfxEgtm_Pwm_initConfig(&pwmConfig, &MODULE_EGTM);

    /* 2. Output configuration */
    outputConfig[0].pin                   = (IfxEgtm_Pwm_ToutMap*)PWM_OUT;             /* PWM output                  */
    outputConfig[0].polarity              = Ifx_ActiveState_high;                     /* Active low/high of pin      */
    outputConfig[0].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                 */
    outputConfig[0].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                  */

    /*3. Channel configuration */

    /* Base channel - CH4 configuration */
    channelConfig[0].timerCh      = IfxEgtm_Pwm_SubModule_Ch_4;          /* Atom channel index                        */
    channelConfig[0].phase        = 0.0f;                               /* Phase shift in radians (range: 0.0 .. 2pi;
                                                                         * only for edge aligned sync channels)      */
    channelConfig[0].duty         = PWM_DUTY;                           /* PWM duty in % (range: 0.0 .. 100.0)       */
    channelConfig[0].dtm          = NULL_PTR;                           /* Attach Dead time configuration            */
    channelConfig[0].output       = &outputConfig[0];                   /* Attach Pin connections and polarities     */
    channelConfig[0].mscOut       = NULL_PTR;                           /* MSC configuration for this channel        */
    channelConfig[0].interrupt    = NULL_PTR;                           /* Attach Interrupt configuration            */

    /* 4. Other configurations */

    pwmConfig.cluster                = IfxEgtm_Cluster_0;                /* Cluster                                   */
    pwmConfig.subModule              = IfxEgtm_Pwm_SubModule_atom;       /* Sub module                                */
    pwmConfig.alignment              = IfxEgtm_Pwm_Alignment_edge;       /* Alignment                                 */
    pwmConfig.syncStart              = TRUE;                            /* Start all channels after initialization   */
    pwmConfig.numChannels            = NUM_OF_PWM_CHANNELS;             /* Number of channels configured             */
    pwmConfig.channels               = channelConfig;                   /* Attach Channel configuration              */
    pwmConfig.frequency              = PWM_FREQUENCY;                   /* PWM frequency                             */
    pwmConfig.clockSource.atom       = IfxEgtm_Cmu_Clk_0;                /* Clock source for atom                     */
    pwmConfig.syncUpdateEnabled      = TRUE;                            /* TRUE: Update compare registers from shadow*/

    /* 5. Call the init function */

    /* Enable EGTM  */
    IfxEgtm_enable(&MODULE_EGTM);

    /* Set the EGTM configurable clock frequency */
    IfxEgtm_Cmu_setClkFrequency(&MODULE_EGTM, IfxEgtm_Cmu_Clk_0, CLK_FREQ );

    /* Enable the CLK clock */
    IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_CLK0);

    /* Initializes the EGTM module for PWM */
    IfxEgtm_Pwm_init(&g_egtmAtomPwm.pwm, &g_egtmAtomPwm.channels[0], &pwmConfig);

    /* Store the current duty value for runtime calls */
    g_egtmAtomPwm.dutyCycles[0] = channelConfig[0].duty;
}

/* This function creates the fade effect for the LED */
void fadeLED(void)
{
    if((g_fadeValue + FADE_STEP) >= PWM_MAX_DUTY)
    {
        g_fadeDir = -1;                                              /* Set the direction of the fade                */
    }
    else if((g_fadeValue - FADE_STEP) <= 0)
    {
        g_fadeDir = 1;                                               /* Set the direction of the fade                */
    }
    g_fadeValue += g_fadeDir * FADE_STEP;                            /* Calculation of the new duty cycle            */
    setDutyCycle(g_fadeValue);                                       /* Set the duty cycle of the PWM                */
}

/* This function sets the duty cycle of the PWM */
void setDutyCycle(float32 dutyCycle)
{
    g_egtmAtomPwm.dutyCycles[0] = dutyCycle;                         /* Set PWM duty cycle                            */

    /* Update duty of all configured channels to requested values immediately */
    IfxEgtm_Pwm_updateChannelsDutyImmediate(&g_egtmAtomPwm.pwm, (float32*)g_egtmAtomPwm.dutyCycles);
}
