/**********************************************************************************************************************
 * \file TMADC_Master_Slave_EGTM_ATOM_Trig.c
 * \copyright Copyright (C) Infineon Technologies AG 2023
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "TMADC_Master_Slave_EGTM_ATOM_Trig.h"
#include "IfxAdc_Tmadc.h"
#include "IfxEgtm_Pwm.h"
#include "IfxEgtm_Trigger.h"
#include "IfxPort.h"
#include "IfxPort_Pinmap.h"
#include "IfxStm.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ADC_SYNCH_NUM_CHANNELS              3                                         /* Number of used channels     */

#define ADC_SYNCH_TMADC_RES_AVAILABLE_PRIO  10                                        /* Interrupt priority           */
#define ADC_SYNCH_PWM_TRIG_OUT_PIN          &IfxEgtm_ATOM0_3_TOUT22_P33_0_OUT /* Pin for EGTM ATOM Trigger to ADC    */
#define ADC_SYNCH_INTERRUPT_OUT_PIN_U       IfxPort_P02_5             /* Pin to watch Result Interrupt from ADC CH U  */
#define ADC_SYNCH_INTERRUPT_OUT_PIN_V       IfxPort_P02_6             /* Pin to watch Result Interrupt from ADC CH V  */
#define ADC_SYNCH_INTERRUPT_OUT_PIN_W       IfxPort_P02_7             /* Pin to watch Result Interrupt from ADC CH W  */

#define IFX_INTPRIO_TMADC_SR0              25                                         /* TMADC SR0 Interrupt priority */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* TMADC handles */
IfxAdc_Tmadc         g_tmadc;                                                    /* TMADC module handle variable     */
IfxAdc_Tmadc_Ch      g_tmadcChannel[ADC_SYNCH_NUM_CHANNELS];                     /* TMADC channels handle array      */

/* Global variable to view the results */
volatile uint16      g_results[ADC_SYNCH_NUM_CHANNELS];                           /* Array of results                 */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/** \brief Function to initialize the TMADC module
 *
 */
IFX_STATIC void initTMADCModule(void);

/** \brief Function to initialize the TMADC channels (Master + Slaves).
 *
 */
IFX_STATIC void initTMADCChannels(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro to define the Interrupt Service Routine */
IFX_INTERRUPT(serviceAdcResult, 0, IFX_INTPRIO_TMADC_SR0);

/* ISR Function that is triggered after the conversion to read the ADC results */
void serviceAdcResult(void)
{
    /* Set the watch pin to high */
    IfxPort_setPinHigh(ADC_SYNCH_INTERRUPT_OUT_PIN_U.port, ADC_SYNCH_INTERRUPT_OUT_PIN_U.pinIndex);

    /* Read the result of each channel */
    g_results[0] = IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel[0]);
    g_results[1] = IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel[1]);
    g_results[2] = IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel[2]);

    /* Set the watch pin to low */
    IfxPort_setPinLow(ADC_SYNCH_INTERRUPT_OUT_PIN_U.port, ADC_SYNCH_INTERRUPT_OUT_PIN_U.pinIndex);
}

/* Function to initialize the TMADC with master/slave configuration */
void initTMADC(void)
{
    initTMADCModule();                                                               /* Initialize the TMADC module  */
    initTMADCChannels();                                                             /* Initialize the TMADC channels*/
    IfxAdc_Tmadc_runModule(&g_tmadc);                                                /* Run the TMADC module         */

    /* Set port pins to watch the events */
    IfxPort_setPinLow(ADC_SYNCH_INTERRUPT_OUT_PIN_U.port, ADC_SYNCH_INTERRUPT_OUT_PIN_U.pinIndex);
    IfxPort_setPinLow(ADC_SYNCH_INTERRUPT_OUT_PIN_V.port, ADC_SYNCH_INTERRUPT_OUT_PIN_V.pinIndex);
    IfxPort_setPinLow(ADC_SYNCH_INTERRUPT_OUT_PIN_W.port, ADC_SYNCH_INTERRUPT_OUT_PIN_W.pinIndex);
    IfxPort_setPinModeOutput(ADC_SYNCH_INTERRUPT_OUT_PIN_U.port, ADC_SYNCH_INTERRUPT_OUT_PIN_U.pinIndex,
                                  IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(ADC_SYNCH_INTERRUPT_OUT_PIN_V.port, ADC_SYNCH_INTERRUPT_OUT_PIN_V.pinIndex,
                                  IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinModeOutput(ADC_SYNCH_INTERRUPT_OUT_PIN_W.port, ADC_SYNCH_INTERRUPT_OUT_PIN_W.pinIndex,
                                  IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
}

/* Function to initialize the TMADC module */
IFX_STATIC void initTMADCModule(void)
{
    IfxAdc_Tmadc_Config tmadcConfig;                           /* TMADC configuration structure                      */
    IfxAdc_Tmadc_InterruptConfig tmadcIntConfig;               /* TMADC interrupt configuration                      */
    IfxAdc_Tmadc_ServRequestConfig tmadcServRequestConfig;     /* TMADC interrupt service request configuration      */

    /* Enable ADC module */
    IfxAdc_enableModule(&MODULE_ADC);

    /* Initialize module to default */
    IfxAdc_Tmadc_initModuleConfig(&tmadcConfig, &MODULE_ADC);

    /* Change TMADC configuration */
    tmadcConfig.id                = IfxAdc_TmadcModule_0;               /* Module ID                                 */
    tmadcConfig.calEnable         = FALSE;                              /* Calibration enabled                       */

    /* Set TMADC Interrupt configuration */
    tmadcIntConfig.node          = IfxAdc_TmadcServReq_0;               /* Select service request node               */
    tmadcIntConfig.eventOp       = IfxAdc_TmadcEventOp_andLogic;        /* Select service request event operation    */
    tmadcIntConfig.eventSel      = IfxAdc_TmadcEventSel_result;         /* Select TMADC event                        */
    tmadcIntConfig.typeOfService = IfxSrc_Tos_cpu0;                     /* Set interrupt provider                    */
    tmadcIntConfig.vmId          = IfxSrc_VmId_0;                       /* Set VM ID for interrupt routing            */
    tmadcIntConfig.priority      = IFX_INTPRIO_TMADC_SR0;               /* Set Channel event priority                */

    tmadcServRequestConfig.intConfig[0] = &tmadcIntConfig;     /* Register correct interrupt configuration           */
    tmadcServRequestConfig.numServReqNodes = 1;                /* Configure number of interrupt service requests     */

    tmadcConfig.srvReqCfg = &tmadcServRequestConfig;           /* Assign the correct service request configuration   */

    /* Initialize TMADC module with updated configuration */
    IfxAdc_Tmadc_initModule(&g_tmadc, &tmadcConfig);

    /* Initialize TMADC service request configuration register 0 */
    {
        Ifx_ADC_TMADC_SR_CFG srCfg;
        srCfg.U = ADC_TMADC0_SR0_CFG.U;
        srCfg.B.EVEN = 0x0007;             /* Service request generation on occurrence of events (channels 0 - 2)    */
        ADC_TMADC0_SR0_CFG.U = srCfg.U;
    }
}

/* Function to initialize the TMADC channels (Master channel U + Slave channels V, W) */
IFX_STATIC void initTMADCChannels(void)
{
    IfxAdc_Tmadc_ChConfig tmadcChannelConfig[ADC_SYNCH_NUM_CHANNELS];              /* TMADC channel configuration   */
    IfxAdc_Tmadc_ChannelServReqConfig tmadcChannelServRequest[ADC_SYNCH_NUM_CHANNELS]; /* TMADC channel srv request */

    /* Common trigger configuration for all channels:
     * Trigger source 36 corresponds to EGTM ATOM trigger routed to TMADC.
     * All channels share the same trigger so they sample synchronously.
     */
    IfxAdc_Tmadc_ChannelTriggerConfig trigger = {{IfxAdc_TmadcTriggerMuxSel_36, IfxAdc_TmadcTriggerMode_fallingEdge},
            {IfxAdc_TmadcTriggerMuxSel_0, IfxAdc_TmadcTriggerMode_disable}, 0};

    /*****************************************************************************************************************/
    /* TMADC Module 0, Channel 0 (Master - Signal U: corresponds to TC3xx EVADC Group 0)                             */
    /*****************************************************************************************************************/

    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&tmadcChannelConfig[0], &MODULE_ADC);

    /* Select the channel ID and the respective result register */
    tmadcChannelConfig[0].id             = IfxAdc_TmadcChannel_0;          /* Channel ID                             */
    tmadcChannelConfig[0].moduleId       = IfxAdc_TmadcModule_0;           /* Select TMADC module                    */
    tmadcChannelConfig[0].samplingTimeNS = 100;                            /* Set sampling time period               */
    tmadcChannelConfig[0].mode           = IfxAdc_TmadcOpMode_oneShot;     /* Select operating mode - one shot       */
    tmadcChannelConfig[0].core           = IfxAdc_TmadcSarCore_0;          /* Select TMADC SAR core                  */

    tmadcChannelConfig[0].resultCfg.resultReg   = IfxAdc_TmadcResultReg_0; /* Configure result register              */
    tmadcChannelConfig[0].resultCfg.waitForRead = TRUE;                    /* Enable wait-for-read mode              */

    tmadcChannelConfig[0].trigger = &trigger;

    /* Set channel service request */
    tmadcChannelServRequest[0].errorNode     = IfxAdc_TmadcServReq_none;    /* Configure Service request error node  */
    tmadcChannelServRequest[0].boundaryNode  = IfxAdc_TmadcServReq_none;    /* Configure Service request boundary    */
    tmadcChannelServRequest[0].resultNode    = IfxAdc_TmadcServReq_0;       /* Configure Service request result node */

    /* Assign configured channel service request to configuration */
    tmadcChannelConfig[0].channelSrvReq = &tmadcChannelServRequest[0];

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel[0], &tmadcChannelConfig[0]);

    /*****************************************************************************************************************/
    /* TMADC Module 0, Channel 1 (Slave 1 - Signal V: corresponds to TC3xx EVADC Group 2)                            */
    /*****************************************************************************************************************/

    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&tmadcChannelConfig[1], &MODULE_ADC);

    /* Select the channel ID and the respective result register */
    tmadcChannelConfig[1].id             = IfxAdc_TmadcChannel_1;          /* Channel ID                             */
    tmadcChannelConfig[1].moduleId       = IfxAdc_TmadcModule_0;           /* Select TMADC module                    */
    tmadcChannelConfig[1].samplingTimeNS = 100;                            /* Set sampling time period               */
    tmadcChannelConfig[1].mode           = IfxAdc_TmadcOpMode_oneShot;     /* Select operating mode - one shot       */
    tmadcChannelConfig[1].core           = IfxAdc_TmadcSarCore_0;          /* Select TMADC SAR core                  */

    tmadcChannelConfig[1].resultCfg.resultReg   = IfxAdc_TmadcResultReg_1; /* Configure result register              */
    tmadcChannelConfig[1].resultCfg.waitForRead = TRUE;                    /* Enable wait-for-read mode              */

    tmadcChannelConfig[1].trigger = &trigger;

    /* Set channel service request */
    tmadcChannelServRequest[1].errorNode     = IfxAdc_TmadcServReq_none;    /* Configure Service request error node  */
    tmadcChannelServRequest[1].boundaryNode  = IfxAdc_TmadcServReq_none;    /* Configure Service request boundary    */
    tmadcChannelServRequest[1].resultNode    = IfxAdc_TmadcServReq_0;       /* Configure Service request result node */

    /* Assign configured channel service request to configuration */
    tmadcChannelConfig[1].channelSrvReq = &tmadcChannelServRequest[1];

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel[1], &tmadcChannelConfig[1]);

    /*****************************************************************************************************************/
    /* TMADC Module 0, Channel 2 (Slave 2 - Signal W: corresponds to TC3xx EVADC Group 3)                            */
    /*****************************************************************************************************************/

    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&tmadcChannelConfig[2], &MODULE_ADC);

    /* Select the channel ID and the respective result register */
    tmadcChannelConfig[2].id             = IfxAdc_TmadcChannel_2;          /* Channel ID                             */
    tmadcChannelConfig[2].moduleId       = IfxAdc_TmadcModule_0;           /* Select TMADC module                    */
    tmadcChannelConfig[2].samplingTimeNS = 100;                            /* Set sampling time period               */
    tmadcChannelConfig[2].mode           = IfxAdc_TmadcOpMode_oneShot;     /* Select operating mode - one shot       */
    tmadcChannelConfig[2].core           = IfxAdc_TmadcSarCore_0;          /* Select TMADC SAR core                  */

    tmadcChannelConfig[2].resultCfg.resultReg   = IfxAdc_TmadcResultReg_2; /* Configure result register              */
    tmadcChannelConfig[2].resultCfg.waitForRead = TRUE;                    /* Enable wait-for-read mode              */

    tmadcChannelConfig[2].trigger = &trigger;

    /* Set channel service request */
    tmadcChannelServRequest[2].errorNode     = IfxAdc_TmadcServReq_none;    /* Configure Service request error node  */
    tmadcChannelServRequest[2].boundaryNode  = IfxAdc_TmadcServReq_none;    /* Configure Service request boundary    */
    tmadcChannelServRequest[2].resultNode    = IfxAdc_TmadcServReq_0;       /* Configure Service request result node */

    /* Assign configured channel service request to configuration */
    tmadcChannelConfig[2].channelSrvReq = &tmadcChannelServRequest[2];

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel[2], &tmadcChannelConfig[2]);
}

/* Function to initialize the EGTM ATOM as PWM channel and configure that to trigger the TMADC */
void initEgtmAtomTrig(void)
{
    if(!IfxEgtm_isEnabled(&MODULE_EGTM))
    {
        IfxEgtm_enable(&MODULE_EGTM);                                                /* Enables the EGTM             */
    }

    {
        /* enable EGTM clock and its clocks */
        float32 frequency = IfxEgtm_Cmu_getModuleFrequency(&MODULE_EGTM);

        IfxEgtm_Cmu_setGclkFrequency(&MODULE_EGTM, frequency);     /* Set the global clock frequency to the max     */
        IfxEgtm_Cmu_setClkFrequency(&MODULE_EGTM, IfxEgtm_Cmu_Clk_0, frequency);              /* Set the CMU CLK0  */
        IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_CLK0);             /* CLK0: used by ATOM           */
    }

    /* Initialize ATOM Channel using PWM driver */
    IfxEgtm_Pwm_Config atomConfig;
    IfxEgtm_Pwm_ChannelConfig channelConfig[1];
    IfxEgtm_Pwm_OutputConfig outputConfig[1];

    IfxEgtm_Pwm_initConfig(&atomConfig, &MODULE_EGTM);

    /* Output configuration */
    outputConfig[0].pin                   = (IfxEgtm_Pwm_ToutMap*)ADC_SYNCH_PWM_TRIG_OUT_PIN;
    outputConfig[0].polarity              = Ifx_ActiveState_low;
    outputConfig[0].outputMode            = IfxPort_OutputMode_pushPull;
    outputConfig[0].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* Channel configuration */
    channelConfig[0].timerCh      = IfxEgtm_Pwm_SubModule_Ch_3;    /* ATOM channel 3                                */
    channelConfig[0].phase        = 0.0f;
    channelConfig[0].duty         = 50.0f;                          /* 50% duty cycle for trigger signal             */
    channelConfig[0].dtm          = NULL_PTR;                       /* No dead-time for trigger                      */
    channelConfig[0].output       = &outputConfig[0];               /* Pin connection                                */
    channelConfig[0].mscOut       = NULL_PTR;
    channelConfig[0].interrupt    = NULL_PTR;                       /* No interrupt for trigger channel               */

    /* Main configuration */
    atomConfig.cluster            = IfxEgtm_Cluster_0;
    atomConfig.subModule          = IfxEgtm_Pwm_SubModule_atom;
    atomConfig.alignment          = IfxEgtm_Pwm_Alignment_edge;
    atomConfig.syncStart          = FALSE;
    atomConfig.numChannels        = 1;
    atomConfig.channels           = channelConfig;
    atomConfig.frequency          = 20.0E3;                         /* PWM frequency: 20 kHz                         */
    atomConfig.clockSource.atom   = IfxEgtm_Cmu_Clk_0;
    atomConfig.syncUpdateEnabled  = TRUE;

    /* Configure EGTM trigger to TMADC: Cluster 0, ATOM source, Channel 3, ADC Trigger Signal 0 */
    IfxEgtm_Trigger_trigToAdc(IfxEgtm_Cluster_0, IfxEgtm_TrigSource_atom,
            IfxEgtm_TrigChannel_3,
            IfxEgtm_Cfg_AdcTriggerSignal_0);                       /* TMADC Triggered by EGTM ATOM0 CH3             */

    {
        IfxEgtm_Pwm pwmHandle;
        IfxEgtm_Pwm_Channel pwmChannels[1];
        IfxEgtm_Pwm_init(&pwmHandle, &pwmChannels[0], &atomConfig);
    }
}
