/**********************************************************************************************************************
 * \file BUS_MPU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "BUS_MPU.h"

/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
/* Functions for "defining protection ranges" of each local memory, and "enable/disable read/write access" to ranges.
 * Make sure to define protection ranges before calling enable/disable read/write functions.
 *
 *-----------Functions for defining protection range-----------------*/
/* The Bus MPU comprises of:
 * 8 read and write protected regions of scratch pad memory SPR(PSPR, DSPR) with enables for reads and writes on a per
 * bus master basis.
 * 8 read and write protected regions of DLMU with enables for reads and writes on a per bus master basis.
 * Individual master read enables for accesses to the local PFlash Bank (LPB).
 * Entire local PFlash is defined for the region, and no registers are used for defining the Lower address and the
 * Upper address.
 *
 *-----------Function that defines DLMU protection range------------*/
/* Protection ranges of DLMU are defined by the Lower address of the region, and the Upper address of the region.
 * The registers, CPUx_ACCENDLMUi_RGNLA (i=0-7) to define the Lower address of the region.
 * CPUx_ACCENDLMUi_RGNUA (i=0-7) to define the Upper address of the region of DLMU.
 */
void define_DLMU0_bus_protection_range(uint32 lowerBoundAddress, uint32 upperBoundAddress, uint8 range)
{
    switch (range)
    {

        case BUS_PROTECTION_RANGE_0:
            CPU0_ACCENDLMU0_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 0 in DLMU0  */
            CPU0_ACCENDLMU0_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 0 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_1:
            CPU0_ACCENDLMU1_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 1 in DLMU0  */
            CPU0_ACCENDLMU1_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 1 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_2:
            CPU0_ACCENDLMU2_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 2 in DLMU0  */
            CPU0_ACCENDLMU2_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 2 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_3:
            CPU0_ACCENDLMU3_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 3 in DLMU0  */
            CPU0_ACCENDLMU3_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 3 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_4:
            CPU0_ACCENDLMU4_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 4 in DLMU0  */
            CPU0_ACCENDLMU4_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 4 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_5:
            CPU0_ACCENDLMU5_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 5 in DLMU0  */
            CPU0_ACCENDLMU5_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 5 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_6:
            CPU0_ACCENDLMU6_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 6 in DLMU0  */
            CPU0_ACCENDLMU6_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 6 in DLMU0  */
            break;

        case BUS_PROTECTION_RANGE_7:
            CPU0_ACCENDLMU7_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 7 in DLMU0  */
            CPU0_ACCENDLMU7_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 7 in DLMU0  */
            break;
    }
}

/*-----------Function that defines SPR protection range------------*/
/* Protection ranges of PSPR/DSPR are defined by the Lower address of the region, and the Upper address of the region.
 * The registers, CPUx_ACCENSPRi_RGNLA (i=0-7) to define the lower address of the region.
 * CPUx_ACCENSPRi_RGNUA (i=0-7) to define the Upper address of the region of PSPR/DSPR.
 */
 void define_SPR0_bus_protection_range(uint32 lowerBoundAddress, uint32 upperBoundAddress, uint8 range)
{

    switch (range)
    {

        case BUS_PROTECTION_RANGE_0:
            CPU0_ACCENSPR0_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 0 in SPR0  */
            CPU0_ACCENSPR0_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 0 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_1:
            CPU0_ACCENSPR1_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 1 in SPR0  */
            CPU0_ACCENSPR1_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 1 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_2:
            CPU0_ACCENSPR2_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 2 in SPR0  */
            CPU0_ACCENSPR2_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 2 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_3:
            CPU0_ACCENSPR3_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 3 in SPR0  */
            CPU0_ACCENSPR3_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 3 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_4:
            CPU0_ACCENSPR4_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 4 in SPR0  */
            CPU0_ACCENSPR4_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 4 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_5:
            CPU0_ACCENSPR5_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 5 in SPR0  */
            CPU0_ACCENSPR5_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 5 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_6:
            CPU0_ACCENSPR6_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 6 in SPR0  */
            CPU0_ACCENSPR6_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 6 in SPR0  */
            break;

        case BUS_PROTECTION_RANGE_7:
            CPU0_ACCENSPR7_RGNLA.U = lowerBoundAddress; /* Set the lower bound of CPU0 Protection Range 7 in SPR0  */
            CPU0_ACCENSPR7_RGNUA.U = upperBoundAddress; /* Set the upper bound of CPU0 Protection Range 7 in SPR0  */
            break;
    }
}
/* ------------------Functions for enable/disable read/write access to the region for CPU0 and CPU1 -----------------*/
/* Make sure to define protection ranges before calling this function.
 *
 * Note: The protection scheme is based on the use of SRI tags to identify the master attempting the access
  (TAG ID based protection), that Indicates which masters are allowed to reach and access to the region.
 */
/*-----------Function for enable DLMU0 read/write access ------------*/
/* Each region of DLMU may be enabled for reads/writes on a per bus master basis using the
 * register CPUx_ACCENDLMUi_RDA/WRA (i=0-7) (Masters 31-0), and CPUx_ACCENDLMUi_RDB/WRB (i=0-7)
 * (Masters 63-32).
 *
 * Protection ranges of DLMU0 are defined by the Lower address of the region, and the Upper address of the region.
 * After enabling the BUS Memory Protection, access to an address 'x' will be allowed only if:
 * lowerBoundAddress <= x < upperBoundAddress and the master tag of the access is enabled.
 * If any of these conditions are not satisfied, the access is seen as invalid.
 *
 * CPU0: TAG-Number= 000001B (Non-safe TAG ID), 000010B (Safe TAG ID).
 * CPU1: TAG-Number= 000101B (Non-safe TAG ID), 000110B (Safe TAG ID).
 */
void enable_DLMU0_read_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {

        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU0_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU0_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU1_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU1_RDA.B.EN02 = 1; /* enable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU1_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU1_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU2_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU2_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU2_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU2_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU3_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU3_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU3_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU3_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU4_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU4_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU4_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU4_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU5_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU5_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU5_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU5_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU6_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU6_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU6_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU6_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU0_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU0_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;
    }
}

/*-----------Function for enable DLMU0 write access ------------*/
void enable_DLMU0_write_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU0_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU0_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU1_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU1_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU1_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU1_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU2_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU2_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU2_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU2_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU3_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU3_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU3_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU3_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU4_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU4_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU4_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU4_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU5_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU5_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU5_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU5_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU6_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU6_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU6_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU6_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENDLMU0_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENDLMU0_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;
    }
}

/*-----------Function for enable SPR0 read/write access ------------*/
/* Each region of PSPR/DSPR may be enabled for reads/writes on a per bus master basis using the
 * register CPUx_ACCENSPRi_RDA/WRA (i=0-7) (Masters 31-0) and CPUx_ACCENSPRi_RDB/WRB (i=0-7)
 * (Masters 63-32).
 *
 * Protection ranges of SPR0 are defined by the Lower address of the region, and the Upper address of the region.
 * After enabling the BUS Memory Protection, access to an address 'x' will be allowed only if:
 * lowerBoundAddress <= x < upperBoundAddress and the master tag of the access is enabled.
 * If any of these conditions are not satisfied, the access is seen as invalid.
 *
 * CPU0: TAG-Number= 000001B (Non-safe TAG ID), 000010B (Safe TAG ID).
 * CPU1: TAG-Number= 000101B (Non-safe TAG ID), 000110B (Safe TAG ID).
 */
void enable_SPR0_read_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR0_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR0_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR1_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR1_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR1_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR1_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR2_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR2_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR2_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR2_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR3_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR3_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR3_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR3_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR4_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR4_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR4_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR4_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR5_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR5_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR5_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR5_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR6_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR6_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR6_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR6_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_RDA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR0_RDA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_RDA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR0_RDA.B.EN06 = 1; /* enable CPU1 */
            }
            break;
    }
}

/*-----------Function for enable SPR0 write access ------------*/
void enable_SPR0_write_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR0_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR0_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR1_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR1_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR1_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR1_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR2_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR2_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR2_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR2_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR3_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR3_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR3_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR3_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR4_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR4_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR4_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR4_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR5_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR5_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR5_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR5_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR6_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR6_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR6_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR6_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_WRA.B.EN01 = 1; /* enable CPU0 */
                CPU0_ACCENSPR0_WRA.B.EN02 = 1; /* enable CPU0 */
            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_WRA.B.EN05 = 1; /* enable CPU1 */
                CPU0_ACCENSPR0_WRA.B.EN06 = 1; /* enable CPU1 */
            }
            break;
    }
}

/*-----------Function for enable LPB0 read access ------------*/
/* Note: TC4xx does not have LPB_SPROT registers. Local PFlash Bank protection
 * is handled differently in TC4xx. This function is kept as a stub for API
 * compatibility with the test framework.
 */
void enable_LPB0_read_bus_protection_range(uint8 desCPU)
{
    (void)desCPU; /* TC4xx: LPB protection registers not available */
}

/*--------------------------------------------Disabling Read/Write Functions-----------------------------------------*/

/*-----------Function for disable DLMU0 read access ------------*/
void disable_DLMU0_read_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU0_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU0_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU1_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU1_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU1_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU1_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU2_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU2_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU2_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU2_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU3_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU3_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU3_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU3_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU4_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU4_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU4_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU4_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU5_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU5_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU5_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU5_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU6_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU6_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU6_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU6_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU0_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU0_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;
    }
}

/*-----------Function for disable DLMU0 write access ------------*/
void disable_DLMU0_write_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU0_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU0_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU1_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU1_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU1_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU1_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU2_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU2_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU2_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU2_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU3_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU3_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU3_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU3_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU4_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU4_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU4_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU4_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU5_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU5_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU5_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU5_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU6_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU6_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU6_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU6_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENDLMU0_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENDLMU0_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENDLMU0_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENDLMU0_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;
    }
}

/*-----------Function for disable SPR0 read access ------------*/
void disable_SPR0_read_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR0_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR0_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR1_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR1_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR1_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR1_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR2_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR2_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR2_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR2_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR3_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR3_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR3_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR3_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR4_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR4_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR4_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR4_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR5_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR5_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR5_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR5_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR6_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR6_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR6_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR6_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_RDA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR0_RDA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_RDA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR0_RDA.B.EN06 = 0; /* disable CPU1 */
            }
            break;
    }
}

/*-----------Function for disable SPR00 write access ------------*/
void disable_SPR0_write_bus_protection_range(uint8 range, uint8 desCPU)
{
    switch (range)
    {
        case BUS_PROTECTION_RANGE_0:
            if (desCPU == 0) {
                CPU0_ACCENSPR0_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR0_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR0_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_1:
            if (desCPU == 0) {
                CPU0_ACCENSPR1_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR1_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR1_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR1_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_2:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR2_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR2_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR2_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR2_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_3:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR3_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR3_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR3_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR3_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_4:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR4_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR4_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR4_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR4_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_5:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR5_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR5_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR5_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR5_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_6:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR6_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR6_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR6_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR6_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;

        case BUS_PROTECTION_RANGE_7:
            if (desCPU == 0)
            {
                CPU0_ACCENSPR0_WRA.B.EN01 = 0; /* disable CPU0 */
                CPU0_ACCENSPR0_WRA.B.EN02 = 0; /* disable CPU0 */

            }
            else if (desCPU == 1)
            {
                CPU0_ACCENSPR0_WRA.B.EN05 = 0; /* disable CPU1 */
                CPU0_ACCENSPR0_WRA.B.EN06 = 0; /* disable CPU1 */
            }
            break;
    }
}

/*-----------Function for disable LPB0 read access ------------*/
/* Note: TC4xx does not have LPB_SPROT registers. This function is kept as a
 * stub for API compatibility with the test framework.
 */
void disable_LPB0_read_bus_protection_range(uint8 desCPU)
{
    (void)desCPU; /* TC4xx: LPB protection registers not available */
}
