/**********************************************************************************************************************
 * \file TMADC.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "TMADC.h"
#include "Ifx_Types.h"
#include "IfxAdc_Tmadc.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* TMADC handler data structure and channel handler structure */
IfxAdc_Tmadc g_tmadc;
IfxAdc_Tmadc_Ch g_tmadcChannel;
IfxAdc_Tmadc_Config g_tmadcConfig;
IfxAdc_Tmadc_ChConfig g_tmadcChannel0Config;
IfxAdc_Tmadc_InterruptConfig g_tmadcIntConfig0;
IfxAdc_Tmadc_ServRequestConfig g_tmadcServRequestConfig;
IfxAdc_Tmadc_ChannelServReqConfig g_tmacChannel0ServRequest;

/* Variable to store the result */
sint16 g_resultTMADC = 0;                                   /* Variable to store the TMADC raw value                    */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Function to initialize the TMADC module */
static void initTMADCModule(void)
{
    /* Enable ADC module */
    IfxAdc_enableModule(&MODULE_ADC);

    /* Initialize module to default */
    IfxAdc_Tmadc_initModuleConfig(&g_tmadcConfig, &MODULE_ADC);

    /* Change TMADC configuration */
    g_tmadcConfig.id                = IfxAdc_TmadcModule_0;             /* Module ID                                 */
    g_tmadcConfig.calEnable         = 1;                                /* Calibration enabled                       */

    /* Initialize TMADC module with updated configuration */
    IfxAdc_Tmadc_initModule(&g_tmadc, &g_tmadcConfig);
}

/* Function to initialize the TMADC channel */
static void initTMADCChannel(void)
{
    /* Initialize the configuration with default values */
    IfxAdc_Tmadc_initChannelConfig(&g_tmadcChannel0Config, &MODULE_ADC);

    /* Change TMADC channel configuration */
    /* Select the channel ID and the respective result register */
    g_tmadcChannel0Config.id             = IfxAdc_TmadcChannel_0;          /* Channel ID                             */
    g_tmadcChannel0Config.moduleId       = IfxAdc_TmadcModule_0;           /* Select TMADC module                    */
    g_tmadcChannel0Config.samplingTimeNS = 100;                            /* Set sampling time period               */
    g_tmadcChannel0Config.mode           = IfxAdc_TmadcOpMode_continuous;  /* Select operating mode - continuous     */
    g_tmadcChannel0Config.core           = IfxAdc_TmadcSarCore_0;          /* Select TMADC SAR core                  */

    g_tmadcChannel0Config.resultCfg.resultReg   = IfxAdc_TmadcResultReg_0; /* Configure result register              */
    g_tmadcChannel0Config.resultCfg.waitForRead = 1;                       /* Enable wait-for-read mode              */

    /* Set channel service request */
    g_tmacChannel0ServRequest.errorNode     = IfxAdc_TmadcServReq_none;    /* Configure Service request error node   */
    g_tmacChannel0ServRequest.boundaryNode  = IfxAdc_TmadcServReq_none;    /* Configure Service request boundary node*/
    g_tmacChannel0ServRequest.resultNode    = IfxAdc_TmadcServReq_0;       /* Configure Service request result node  */

    /* Assign configured channel service request to configuration */
    g_tmadcChannel0Config.channelSrvReq = &g_tmacChannel0ServRequest;

    /* Initialize the channel */
    IfxAdc_Tmadc_initChannel(&g_tmadcChannel, &g_tmadcChannel0Config);
}

/* In this function, the TMADC module is initialized */
void init_TMADC(void)
{
    /* Initialize the TMADC module */
    initTMADCModule();

    /* Initialize the channel */
    initTMADCChannel();

    /* Run the TMADC module */
    IfxAdc_Tmadc_runModule(&g_tmadc);
}

/* This function gets the result of the most recent conversion */
sint16 run_TMADC(void)
{
    g_resultTMADC = (sint16)IfxAdc_Tmadc_readChannelResult(&g_tmadcChannel);  /* Get the TMADC raw value              */
    return g_resultTMADC;
}
