/**********************************************************************************************************************
 * \file DSPR_TEST.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "IfxVmt.h"
#include "IfxVmt_reg.h"
#include "IfxVmt_bf.h"
#include "IfxPort.h"
#include "DSPR_TEST.h"
#include "board.h"
#include BOARD_PIN_FILE

/*********************************************************************************************************************/
/*----------------------------------------------------- Macros ------------------------------------------------------*/
/*********************************************************************************************************************/
/* Use TC4xx board LED definitions from pin.h */
#define LED_PASS                        LED_1                            /* LED for test success                     */
#define LED_FAIL                        LED_2                            /* LED for test failure                     */

/* VMT MBIST Error flags */
#define VMT_CORRECTABLE_ERROR_FLAG      ((unsigned int)IFX_VMT_MC_ECCD_CERR_MSK << IFX_VMT_MC_ECCD_CERR_OFF)
#define VMT_UNCORRECTABLE_ERROR_FLAG    ((unsigned int)IFX_VMT_MC_ECCD_UCERR_MSK << IFX_VMT_MC_ECCD_UCERR_OFF)

#define VMT_CLEAR_FAULTSTS_OPERR0_MSK   0x3E                            /* Mask for clearing bit 0 of OPERR bitfield*/

#define Single_Bit_Error   0x01
#define Double_Bit_Error   0x03
/*********************************************************************************************************************/
/*--------------------------------------------------Global variables-------------------------------------------------*/
/*********************************************************************************************************************/
/* These global variable are not used during the MBIST and so can be located in DSPR*/
volatile uint32 g_errorInjection = TRUE;
volatile uint32 *mem_ptr = (uint32 *)0x70000050;
/* use 0x1 for single error injection and 0x3 for double error injection */
uint32 injected_error = Single_Bit_Error;

/*********************************************************************************************************************/
/*--------------------------------------------------Function Prototypes----------------------------------------------*/
/*********************************************************************************************************************/
static uint32 get_VMT_MBIST_Errors(IfxVmt_MbistSel mbistSel);
static void clear_VMT_MBIST_Errors(IfxVmt_MbistSel mbistSel);

/*********************************************************************************************************************/
/*------------------------------------------------Function Implementations-------------------------------------------*/
/*********************************************************************************************************************/
/* This function inject an error and tests CPU0 DSPR memory using MBIST, no context switch is allowed during the test */
void CPU0_DSPR_MTU_Test()
{
    Ifx_VMT_MC *mc;

    /* Initialize the used LEDs */
    /* Setup Port Pin working mode to control the LEDs */
    IfxPort_setPinMode(LED_PASS, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinMode(LED_FAIL, IfxPort_Mode_outputPushPullGeneral);

    /* Turn off LEDs */
    IfxPort_setPinHigh(LED_PASS);
    IfxPort_setPinHigh(LED_FAIL);

    *mem_ptr=5;

    /* Enable VMT clock */
    IfxVmt_enableModule(&MODULE_VMT0);

    /* Check if any error flag is set.
     * After any System Reset: For each and every SSH in the system, the UCE alarm status in the SMU, the ECCD.UCERR
     * (Consequently also SERR) and the FAULTSTS.OPERR[0] are set.
     */
    if(get_VMT_MBIST_Errors(IfxVmt_MbistSel_cpu0Dspr))
    {
        /* Clear the alarm status flags to enable a correct error tracking */
        clear_VMT_MBIST_Errors(IfxVmt_MbistSel_cpu0Dspr);
    }

    /* Error injection is selected */
    if(g_errorInjection == TRUE)
    {
        /* Get MC instance pointer for CPU0 DSPR */
        mc = IfxVmt_getDmtuMcInstancePtr(IfxVmt_MbistSel_cpu0Dspr);

        mc->ECCS.B.ECCMAP = 1;
        __isync();

        *mem_ptr=*mem_ptr ^ injected_error;
        __dsync();

        mc->ECCS.B.ECCMAP = 0;
        __isync();

        /*
         * Reading the address mem_ptr at this stage will trigger the ECC, uncomment for test purposes
         * In case a single error injected: The error will be corrected
         * In case a double error injected: The CPU will trap due to data integrity error (class 4, ID 6)
         * volatile uint32  VAR1=*mem_ptr;
         */
    }

    /* Run the Non-Destructive Test (NDT) on CPU0 DSPR */
    /* In TC4xx, CPU0 DSPR maps to a single memory controller (IfxVmt_MbistSel_cpu0Dspr) */

    /* Get MC instance pointer for CPU0 DSPR */
    mc = IfxVmt_getDmtuMcInstancePtr(IfxVmt_MbistSel_cpu0Dspr);

    /* Disable tracking of unnecessary errors */
    mc->ALMSRCS.B.MISCE = 0U;
    mc->ALMSRCS.B.OPENE = 0U;

    /* Enable CPU0 DSPR SSH */
    IfxVmt_enableMbistShell(IfxVmt_MbistSel_cpu0Dspr);
    __isync();
    while(IfxVmt_isAutoInitRunning(IfxVmt_MbistSel_cpu0Dspr))
    {}
    /* After this step everything in DSPR is unavailable (CSA, stack, heap, global variables...) */

    /* Clear all the error bits */
    mc->ECCD.U = 0x10;

    /* Config the NDT */
    mc->CONFIG0.U   = 0x4005;
    mc->CONFIG1.U   = 0x5008;
    mc->MCONTROL.U  = 0x4009;
    while(mc->MSTATUS.B.DONE != 0){};

    mc->MCONTROL.B.START = 0;
    while(mc->MSTATUS.B.DONE != 1){};

    /* Disable CPU0 DSPR SSH */
    IfxVmt_disableMbistShell(IfxVmt_MbistSel_cpu0Dspr);
    __isync();
    while(IfxVmt_isAutoInitRunning(IfxVmt_MbistSel_cpu0Dspr))
    {}

    /* After this step everything in DSPR is available again (CSA, stack, heap, global variables...) */

    /* Check the test result */
    /* The expected value of ECCD in case of correctable error is 0x23 */
    if((get_VMT_MBIST_Errors(IfxVmt_MbistSel_cpu0Dspr) & VMT_CORRECTABLE_ERROR_FLAG) != 0)
    {
        if(injected_error == Single_Bit_Error)
        {
            IfxPort_setPinLow(LED_PASS);
        }
        else
        {
            IfxPort_setPinLow(LED_FAIL);
        }
    }
    /* The expected value of ECCD in case of uncorrectable error is 0x25 */
    else if((get_VMT_MBIST_Errors(IfxVmt_MbistSel_cpu0Dspr) & VMT_UNCORRECTABLE_ERROR_FLAG) != 0)
    {
        if(injected_error == Double_Bit_Error)
        {
            IfxPort_setPinLow(LED_PASS);
        }
        else
        {
            IfxPort_setPinLow(LED_FAIL);
        }
    }
    else
    {
        /* Turn On FAIL LED: Error not detected */
        IfxPort_setPinLow(LED_FAIL);
    }
}

/* Get MBIST error flags of a specific memory */
static uint32 get_VMT_MBIST_Errors(IfxVmt_MbistSel mbistSel)
{
    Ifx_VMT_MC *mc = IfxVmt_getDmtuMcInstancePtr(mbistSel);

    return (uint32)(mc->ECCD.U & (IFXVMT_ERROR_FLAGS_MASK));
}

/* Clear MCi_ECCD and MCi_FAULTSTS error flags of a specific memory raised by a System Reset */
static void clear_VMT_MBIST_Errors(IfxVmt_MbistSel mbistSel)
{
    Ifx_VMT_MC *mc = IfxVmt_getDmtuMcInstancePtr(mbistSel);

    mc->ECCD.B.SERR = 0;                                    /* Error Detected flag                          */
    mc->ECCD.B.UCERR = 0;                                   /* UnCorrectable Error (UCE) alarm flag         */
    mc->FAULTSTS.B.OPERR &= VMT_CLEAR_FAULTSTS_OPERR0_MSK;  /* SSH Critical Operation Error flags: clear
     * bit 0, set by any System Reset               */

    IfxVmt_clearErrorTracking(mbistSel);                    /* Clear the error tracking registers (ETRR)    */
}
