/**********************************************************************************************************************
 * \file EGTM_TOM_3_Phase_Inverter_PWM.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "EGTM_TOM_3_Phase_Inverter_PWM.h"
#include "Ifx_Types.h"
#include "IfxEgtm_Pwm.h"
#include "IfxPort.h"
#include "IfxPort_Pinmap.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define NUM_OF_CHANNELS         (3)                                    /* Number of PWM complementary pairs          */
#define PWM_FREQUENCY           (20.0E3)                               /* PWM frequency in [Hz]                      */
#define ISR_PRIORITY_TOM        (20)                                   /* Interrupt priority number                  */

#define PHASE_U_HS              &IfxEgtm_TOM1_2_TOUT12_P00_3_OUT      /* Pin driven by the PWM, P00.3               */
#define PHASE_U_LS              &IfxEgtm_TOM1_2N_TOUT13_P00_4_OUT     /* Pin driven by the PWM, P00.4               */
#define PHASE_V_HS              &IfxEgtm_TOM1_4_TOUT14_P00_5_OUT      /* Pin driven by the PWM, P00.5               */
#define PHASE_V_LS              &IfxEgtm_TOM1_4N_TOUT15_P00_6_OUT     /* Pin driven by the PWM, P00.6               */
#define PHASE_W_HS              &IfxEgtm_TOM1_6_TOUT16_P00_7_OUT      /* Pin driven by the PWM, P00.7               */
#define PHASE_W_LS              &IfxEgtm_TOM1_6N_TOUT17_P00_8_OUT     /* Pin driven by the PWM, P00.8               */

#define PHASE_U_DUTY            (25.0f)                                /* Initial PWM duty cycle of phase U in [%]   */
#define PHASE_V_DUTY            (50.0f)                                /* Initial PWM duty cycle of phase V in [%]   */
#define PHASE_W_DUTY            (75.0f)                                /* Initial PWM duty cycle of phase W in [%]   */
#define PHASE_DUTY_STEP         (10.0f)                                /* PWM duty cycle step in [%]                 */
#define PHASE_DUTY_MIN          (10.0f)                                /* Minimum duty cycle in [%]                  */
#define PHASE_DUTY_MAX          (90.0f)                                /* Maximum duty cycle in [%]                  */

#define LED                 &MODULE_P03, 9           /* LED which will be toggled in Interrupt Service Routine (ISR) */

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
        IfxEgtm_Pwm          pwm;                               /* PWM Driver handle                                 */
        IfxEgtm_Pwm_Channel  channels[NUM_OF_CHANNELS];         /* Array containing channel data after configuration */
        float32              dutyCycles[NUM_OF_CHANNELS];       /* Duty Cycle values to hold                         */
        float32              phases[NUM_OF_CHANNELS];           /* PhaseShift values to hold                         */
        IfxEgtm_Pwm_DeadTime deadTimes[NUM_OF_CHANNELS];        /* Dead time values to hold                          */
} EgtmTom3phInv;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IFX_STATIC EgtmTom3phInv g_egtmTom3phInv;

/*********************************************************************************************************************/
/*-----------------------------------------------Function Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Function Implementations-----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define the Interrupt Service Routine. */
IFX_INTERRUPT(interruptEgtmTom, 0, ISR_PRIORITY_TOM);

/* Interrupt Service Routine of the TOM */
void interruptEgtmTom(void)
{
    IfxPort_togglePin(LED);                                                      /* Toggle the LED                   */
}

/* Period interrupt callback function */
void IfxEgtm_periodEventFunction(void *data)
{

}

/* This function initializes the TOM */
void initEgtmTomPwm(void)
{
    /** Configuration variables
     * Neither application (in most of the cases) nor the PWM driver need configuration variables post initialization.
     * Hence it is recommended to define such variables within the function (STACK).
     */
    IfxEgtm_Pwm_Config config;                               /* Main PWM config structure                            */
    IfxEgtm_Pwm_ChannelConfig channelConfig[NUM_OF_CHANNELS];/* Array containing configuration for each channel      */
    IfxEgtm_Pwm_DtmConfig dtmConfig[NUM_OF_CHANNELS];        /* Only needed if using DTM module                      */
    IfxEgtm_Pwm_InterruptConfig interruptConfig;             /* Only needed if using interrupt. Can also be an array */
    IfxEgtm_Pwm_OutputConfig output[NUM_OF_CHANNELS];        /* Only needed if connected to pin                      */

    /* 1. Config structure initialization */
    IfxEgtm_Pwm_initConfig(&config, &MODULE_EGTM);

    /* 2. Output configuration */

    /* CH0 configurations - Phase U */
    output[0].pin                   = (IfxEgtm_Pwm_ToutMap*)PHASE_U_HS;         /* Phase U PWM High-side             */
    output[0].complementaryPin      = (IfxEgtm_Pwm_ToutMap*)PHASE_U_LS;         /* Phase U PWM Low-side              */
    output[0].polarity              = Ifx_ActiveState_high;                     /* Active high for high-side         */
    output[0].complementaryPolarity = Ifx_ActiveState_high;                     /* Active high for low-side          */
    output[0].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[0].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* CH1 configurations - Phase V */
    output[1].pin                   = (IfxEgtm_Pwm_ToutMap*)PHASE_V_HS;         /* Phase V PWM High-side             */
    output[1].complementaryPin      = (IfxEgtm_Pwm_ToutMap*)PHASE_V_LS;         /* Phase V PWM Low-side              */
    output[1].polarity              = Ifx_ActiveState_high;                     /* Active high for high-side         */
    output[1].complementaryPolarity = Ifx_ActiveState_high;                     /* Active high for low-side          */
    output[1].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[1].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* CH2 configurations - Phase W */
    output[2].pin                   = (IfxEgtm_Pwm_ToutMap*)PHASE_W_HS;         /* Phase W PWM High-side             */
    output[2].complementaryPin      = (IfxEgtm_Pwm_ToutMap*)PHASE_W_LS;         /* Phase W PWM Low-side              */
    output[2].polarity              = Ifx_ActiveState_high;                     /* Active high for high-side         */
    output[2].complementaryPolarity = Ifx_ActiveState_high;                     /* Active high for low-side          */
    output[2].outputMode            = IfxPort_OutputMode_pushPull;              /* Output mode                       */
    output[2].padDriver             = IfxPort_PadDriver_cmosAutomotiveSpeed1;   /* Pad driver                        */

    /* 3. Dead-time configuration */
    dtmConfig[0].deadTime.rising    = 0.5e-6f;              /* Rising Dead time in seconds                           */
    dtmConfig[0].deadTime.falling   = 0.5e-6f;              /* Falling Dead time in seconds                          */

    dtmConfig[1].deadTime.rising    = 0.5e-6f;              /* Rising Dead time in seconds                           */
    dtmConfig[1].deadTime.falling   = 0.5e-6f;              /* Falling Dead time in seconds                          */

    dtmConfig[2].deadTime.rising    = 0.5e-6f;              /* Rising Dead time in seconds                           */
    dtmConfig[2].deadTime.falling   = 0.5e-6f;              /* Falling Dead time in seconds                          */

    /* 4. [Optional] Interrupt configuration for base channel */
    interruptConfig.mode          = IfxEgtm_IrqMode_pulseNotify; /* IRQ mode of interrupt                            */
    interruptConfig.isrProvider   = IfxSrc_Tos_cpu0;             /* Type of Service                                  */
    interruptConfig.priority      = ISR_PRIORITY_TOM;            /* Interrupt priority                               */
    interruptConfig.vmId          = IfxSrc_VmId_0;               /* VM ID for interrupt routing (TC4xx)               */
    /* Connect callback function for period event interrupt */
    interruptConfig.periodEvent   = IfxEgtm_periodEventFunction;
    interruptConfig.dutyEvent     = NULL_PTR;                /* Do not use duty event interrupt                       */

    /* 5. Channel configuration */

    /* Base channel - CH0 configuration (Phase U) */
    channelConfig[0].timerCh      = IfxEgtm_Pwm_SubModule_Ch_0;  /* TOM channel index to be used for base channel   */
    channelConfig[0].phase        = 0.0f;                        /* Phase shift in radians                          */
    channelConfig[0].duty         = PHASE_U_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)             */
    channelConfig[0].dtm          = &dtmConfig[0];               /* Attach Dead time configuration for this channel */
    channelConfig[0].output       = &output[0];                  /* Attach Pin connections and polarities            */
    channelConfig[0].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[0].interrupt    = &interruptConfig;            /* Attach Interrupt configuration                   */

    /* Sync channel CH1 configuration (Phase V) */
    channelConfig[1].timerCh      = IfxEgtm_Pwm_SubModule_Ch_1;  /* TOM channel index to be used for sync channel   */
    channelConfig[1].phase        = 0.0f;                        /* Phase shift in radians                          */
    channelConfig[1].duty         = PHASE_V_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)             */
    channelConfig[1].dtm          = &dtmConfig[1];               /* Dead time configuration for this channel        */
    channelConfig[1].output       = &output[1];                  /* Pin connections and polarities                   */
    channelConfig[1].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[1].interrupt    = NULL_PTR;                    /* Interrupt configuration for this channel         */

    /* Sync channel CH2 configuration (Phase W) */
    channelConfig[2].timerCh      = IfxEgtm_Pwm_SubModule_Ch_2;  /* TOM channel index to be used for sync channel   */
    channelConfig[2].phase        = 0.0f;                        /* Phase shift in radians                          */
    channelConfig[2].duty         = PHASE_W_DUTY;                /* PWM duty in % (range: 0.0 .. 100.0)             */
    channelConfig[2].dtm          = &dtmConfig[2];               /* Dead time configuration for this channel        */
    channelConfig[2].output       = &output[2];                  /* Pin connections and polarities                   */
    channelConfig[2].mscOut       = NULL_PTR;                    /* MSC configuration for this channel               */
    channelConfig[2].interrupt    = NULL_PTR;                    /* Interrupt configuration for this channel         */

    /* 6. Other configurations */
    config.cluster                = IfxEgtm_Cluster_0;                 /* Cluster                                    */
    config.subModule              = IfxEgtm_Pwm_SubModule_tom;         /* Sub module: TOM (not ATOM)                 */
    config.alignment              = IfxEgtm_Pwm_Alignment_center;      /* Center-aligned PWM                         */
    config.syncStart              = TRUE;                              /* Start all channels after init              */
    config.numChannels            = NUM_OF_CHANNELS;                   /* Number of channels configured              */
    config.channels               = channelConfig;                     /* Attach Channel configuration               */
    config.frequency              = PWM_FREQUENCY;                     /* PWM frequency                              */
    config.clockSource.tom        = IfxEgtm_Cmu_Clk_0;                /* Clock source for TOM                       */
    config.dtmClockSource         = IfxEgtm_Dtm_ClockSource_cmuClock0; /* Clock source for dtm                       */
    config.syncUpdateEnabled      = TRUE;                              /* TRUE: Update compare registers from shadow
                                                                        * at the end of period */

    /* 7. Enable EGTM module and configure clocks */
    if(!IfxEgtm_isEnabled(&MODULE_EGTM))
    {
        float32 frequency;
        /* Enable EGTM, it is necessary if the EGTM is not initialized earlier */
        IfxEgtm_enable(&MODULE_EGTM);

        frequency = IfxEgtm_Cmu_getModuleFrequency(&MODULE_EGTM);
        /* Set the global clock frequency to the max */
        IfxEgtm_Cmu_setGclkFrequency(&MODULE_EGTM, frequency);
        /* Set the CMU CLK0 */
        IfxEgtm_Cmu_setClkFrequency(&MODULE_EGTM, IfxEgtm_Cmu_Clk_0, frequency);
        /* Enable the FXU clock */
        IfxEgtm_Cmu_enableClocks(&MODULE_EGTM, IFXEGTM_CMU_CLKEN_CLK0);
    }

    /* 8. Call the init function */
    IfxEgtm_Pwm_init(&g_egtmTom3phInv.pwm, &g_egtmTom3phInv.channels[0], &config);

    /* Store the current duty values for runtime calls */
    g_egtmTom3phInv.dutyCycles[0] = channelConfig[0].duty;
    g_egtmTom3phInv.dutyCycles[1] = channelConfig[1].duty;
    g_egtmTom3phInv.dutyCycles[2] = channelConfig[2].duty;
    /* Store the current dead time values for runtime calls */
    g_egtmTom3phInv.deadTimes[0] = channelConfig[0].dtm->deadTime;
    g_egtmTom3phInv.deadTimes[1] = channelConfig[1].dtm->deadTime;
    g_egtmTom3phInv.deadTimes[2] = channelConfig[2].dtm->deadTime;

    IfxPort_setPinModeOutput(LED, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);   /* Set pin mode         */
}

/* This function sets the duty cycle of the PWM signals */
void updateEgtmTomPwmDutyCycles(void)
{
    /* Increment PWM duty cycles */
    g_egtmTom3phInv.dutyCycles[0] += PHASE_DUTY_STEP;
    g_egtmTom3phInv.dutyCycles[1] += PHASE_DUTY_STEP;
    g_egtmTom3phInv.dutyCycles[2] += PHASE_DUTY_STEP;

    /* Limit PWM duty cycles between PHASE_DUTY_MIN and PHASE_DUTY_MAX */
    if(g_egtmTom3phInv.dutyCycles[0] >= PHASE_DUTY_MAX)
    {
        g_egtmTom3phInv.dutyCycles[0] = PHASE_DUTY_MIN;
    }
    if(g_egtmTom3phInv.dutyCycles[1] >= PHASE_DUTY_MAX)
    {
        g_egtmTom3phInv.dutyCycles[1] = PHASE_DUTY_MIN;
    }
    if(g_egtmTom3phInv.dutyCycles[2] >= PHASE_DUTY_MAX)
    {
        g_egtmTom3phInv.dutyCycles[2] = PHASE_DUTY_MIN;
    }

    /* Update duty of all configured channels to requested values immediately */
    IfxEgtm_Pwm_updateChannelsDutyImmediate(&g_egtmTom3phInv.pwm, (float32*)g_egtmTom3phInv.dutyCycles);
}
